Changes to support arm64 in the systemd EFI stub
snapcore/core-initrd pull request #32
Opened 2021-07-27 10:17 UTC by alfonsosanchezbeato

First draft to support aarch64 in EFI stub. Main changes are

- The way the kernel is started in arm64 is different to x86 one: instead of using boot parameters, it takes a device tree that needs to be modified to specify the initrd location. Also, we are not calling it directly but via the kernel EFI stub, that takes command line from the EFI parameters so we do not need to touch them in systemd stub.
- objcopy does not support PE/COFF for aarch64, so to create kernel.efi we use llvm-objcopy instead. Even in that case, llvm-objcopy seems to be buggy and some fields in the PE headers need to be modified from the script.

I think that changes in sources need to go to a patch, but for the moment I am proposing directly to ease review.

2021-07-27 13:30 UTC, anonymouse64 commented
(I didn't review, but I trust @alfonsosanchezbeato so I let the CI run to see what happens)

2021-07-27 16:50 UTC, anonymouse64 commented
Ah actually, due to how the spread setup is for core-initrd, the CI cannot run on a branch from a fork like Alfonso has done here, not sure how folks want to handle this...

2021-08-11 07:34 UTC, stulluk requested changes

2021-08-11 07:34 UTC, stulluk commented on bin/ubuntu-core-aarch64-efi
> +#!/usr/bin/python3
Please add Canonical header and the purpose

2021-08-12 07:47 UTC, stulluk commented on vendor/systemd/src/boot/efi/stdclib.c
> +
Please explain the purpose of this function

2021-08-12 07:47 UTC, stulluk commented on vendor/systemd/src/boot/efi/linux-aarch64.c
> +    { 0xb1b621d5, 0xf19c, 0x41a5, {0x83, 0x0b, 0xd9, 0x15, 0x2c, 0x69, 0xaa, 0xe0} }
Where does those magic values come from ?

2021-08-17 08:48 UTC, alfonsosanchezbeato commented
Overriden by https://github.com/snapcore/core-initrd/pull/35

2021-08-17 08:48 UTC, closed without merging