Switch to using llvm-objcopy instead of objcopy to create kernel.efi
snapcore/core-initrd pull request #89
Opened 2022-03-18 10:21 UTC by alfonsosanchezbeato

We switch to llvm-objcopy to be able to build kernel.efi for arm64 and
other non-x86 architectures in the future.

2022-03-18 10:41 UTC, xnox commented
I like switching to llvm-objcopy on all arches, even if it is driven by better !x86 support.
Dropping exact offsets/locations within kernel.efi should be harmless, and tightly packed aligned sections feels more correct, instead of hard-coded addresses.
Before merging this, I will cherrypick this patch locally to double check that kernel.efi doesn't regress for me on x86.

2022-03-18 11:38 UTC, valentindavid approved these changes

2022-03-22 10:58 UTC, alfonsosanchezbeato commented
@xnox hey, did you have time to test on your side in the end?

2022-03-22 14:33 UTC, xnox requested changes

2022-03-22 15:10 UTC, alfonsosanchezbeato commented on debian/control
> +               llvm,
Right, I've fixed that now.

2022-03-23 10:43 UTC, alfonsosanchezbeato commented
I tested the changes locally to build arm64 and x86 kernel.efi images, and it booted successfully in both cases.

2022-03-23 10:57 UTC, xnox approved these changes
This works for me. It is unfortunate that one has to install all of llvm tooling (like 300MB) just to use llvm-objcopy alone, but I guess such is life.

Also note that llvm-defaults were just bumped in jammy from 13 to 14. Without retrying all the tests, it seems that the cherry-picked patches in llvm-toolchain-13 to fix usage are present in our upload of llvm-toolchain-14 hence everything should still work fine.

I think this is good to merge and upload into the PPA.

2022-03-23 11:01 UTC, merged